export const TOKEN_PLACEHOLDER = 'token';
export const TRANSACTION_TYPE_PLACEHOLDER = 'transactionType';
export const TRANSACTION_OBJECT_PLACEHOLDER = 'transactionObject';
export const TRANSACTION_TYPE = {
    SONG_PUBLISH: "SONG_PUBLISH",
    SONG_RAISE_TIER: "SONG_RAISE_TIER",
    ALBUM_PUBLISH: "ALBUM_PUBLISH",
    ALBUM_RAISE_TIER: "ALBUM_RAISE_TIER"
}